import 'dotenv/config';
import { chromium } from 'playwright-core';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import { randomUUID } from 'node:crypto';import { PrismaClient } from '@prisma/client';
const db=new PrismaClient(),email='browser-'+randomUUID()+'@example.test';
if(!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL).hostname))throw new Error('Browser tests require a local database.');
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,timeout:20000,args:['--no-sandbox','--disable-gpu','--no-first-run']});
const page=await browser.newPage(),errors=[],report={routes:[],checks:[]};page.on('pageerror',e=>errors.push(e.message));
try{
 const sitemap=await fs.readFile('dist/sitemap.xml','utf8');const paths=[...sitemap.matchAll(/<loc>https:\/\/[^<]+?(\/[^<]*)<\/loc>/g)].map(m=>m[1]);paths.push('/newsletter-confirmed');
 for(const route of paths){await page.goto('http://localhost:3100'+route,{waitUntil:'domcontentloaded'});await page.locator('h1').first().waitFor({timeout:80000});const heading=(await page.locator('h1').first().innerText()).trim();assert.ok(heading,route);assert.ok(!/couldn.t load|page not found/i.test(heading),route+' must render its published content');report.routes.push({route,status:'connected browser heading passed'});}
 assert.deepEqual(errors,[]);report.checks.push('All routes render without JavaScript errors');
 await page.goto('http://localhost:3100/things-to-do-in-victoria-falls');const search=page.getByPlaceholder('Search experiences — e.g. Chobe Safari, Sunset Cruise, Helicopter Flight...');await search.fill('no-matching-experience-12345');await page.getByText('No experiences match your search phrase. Try searching for safari, cruise, helicopter, or tour.',{exact:true}).waitFor();await search.fill('Chobe');assert.ok(await page.locator('a[href^="/things-to-do/"]').count()>0);report.checks.push('Experience search shows matching records and a genuine empty state');
 await page.goto('http://localhost:3100/client-gallery');await page.getByRole('button',{name:'Enlarge client gallery photo 1',exact:true}).click();await page.getByRole('button',{name:'Next image',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Close gallery'}).count(),0);report.checks.push('Client gallery opens, advances and closes with Escape');
 await page.goto('http://localhost:3100/contact');await page.getByPlaceholder('e.g. Tendai Moyo').fill('Browser Traveller');await page.getByPlaceholder('name@example.com').fill(email);await page.locator('textarea').fill('Browser integration enquiry with preserved inputs.');await page.waitForTimeout(1700);
 let first=true;const keys=[];await page.route('**/api/v1/enquiries',async route=>{keys.push(route.request().headers()['idempotency-key']);if(first){first=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Simulated service interruption.'})});}else await route.continue();});
 await page.getByRole('button',{name:'Send Message',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByPlaceholder('name@example.com').inputValue(),email);await page.getByRole('button',{name:'Send Message',exact:true}).click();await page.getByText('Saved enquiry reference:',{exact:false}).waitFor();assert.equal(keys[0],keys[1]);const contact=await db.enquiry.findFirstOrThrow({where:{email,source:'contact'}});assert.ok(contact.reference.startsWith('OH-'));report.checks.push('Contact failure retains fields; retry reuses durable idempotency key and saves a reference');await page.unroute('**/api/v1/enquiries');
 await page.goto('http://localhost:3100');await page.getByRole('button',{name:'Plan My Holiday',exact:true}).first().click();await page.getByRole('button',{name:'Start Guided Builder',exact:false}).click();
 for(let i=0;i<7;i++)await page.getByRole('button',{name:/^Continue(?: to Send Plan)?$/}).click();
 const form=page.locator('form').filter({has:page.getByRole('button',{name:'Send Me My Custom Itinerary Quote',exact:true})});await form.locator('input[type=text]').first().fill('Builder Traveller');await form.locator('input[type=email]').fill(email);await page.getByRole('button',{name:'Send Me My Custom Itinerary Quote',exact:true}).click();await page.getByText('Saved enquiry reference:',{exact:false}).waitFor();const builder=await db.enquiry.findFirstOrThrow({where:{email,source:'holiday-builder'}});assert.ok(builder.selectionSnapshot.items.length>0);report.checks.push('Eight-stage builder saves selected IDs, contact details and server-verified estimate');
 await page.goto('http://localhost:3100');const news=page.locator('form').filter({has:page.getByPlaceholder('Enter your email address...')});await news.locator('input[type=email]').fill(email);assert.equal(await news.getByRole('button',{name:'Subscribe',exact:true}).isDisabled(),true);await news.locator('input[type=checkbox]').check();await page.waitForTimeout(1700);await news.getByRole('button',{name:'Subscribe',exact:true}).click();await page.getByText('Confirmation email delivery is awaiting configuration',{exact:false}).waitFor();assert.equal((await db.subscription.findUniqueOrThrow({where:{email}})).status,'pending');report.checks.push('Newsletter requires consent and shows pending configuration truthfully');
 await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:3100');await page.locator('h1').waitFor();await page.screenshot({path:'.local/mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);report.checks.push('Mobile homepage fits viewport');
 assert.deepEqual(errors,[]);await fs.writeFile('docs/browser-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({routes:report.routes.length,checks:report.checks,errors},null,2));
}finally{
 await browser.close();const enquiries=await db.enquiry.findMany({where:{email}}),sub=await db.subscription.findUnique({where:{email}});await db.notification.deleteMany({where:{OR:[{enquiryId:{in:enquiries.map(e=>e.id)}},...(sub?[{subscriptionId:sub.id}]:[])]}});await db.enquiry.deleteMany({where:{email}});await db.subscription.deleteMany({where:{email}});await db.submissionKey.deleteMany({where:{OR:enquiries.map(e=>({result:{path:['reference'],equals:e.reference}}))}}).catch(()=>{});await db.$disconnect();
}
